services:
  - type: web
    name: money-maker-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        value: https://money-maker-platform.vercel.app
      - key: JWT_EXPIRE
        value: 7d
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100